# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [30]:
print(np.__version__)
print(np.show_config())

1.26.1
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1756924716496
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.1
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30152
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30152
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.3
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows


#### 3. Create a null vector of size 10

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array

In [5]:
arr = np.zeros(10)
arr.nbytes

80

#### 5.  How to get the documentation of the numpy add function from the command line? 

In [8]:
help(np.add)
# np.info(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [10]:
z = np.zeros(10)
z[4] = 1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49

In [18]:
vector = np.arange(10, 50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last)

In [26]:
vector[::-1]
# np.flip(vector)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [29]:
values = np.arange(0, 9)
matrix = values.reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [34]:
a = np.array([1, 2, 0, 0, 4, 0])
result = np.nonzero(a)[0]
result

array([0, 1, 4], dtype=int64)

#### 11. Create a 3x3 identity matrix

In [35]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [36]:
np.random.rand(3, 3, 3)

array([[[0.35414244, 0.68215506, 0.72275404],
        [0.7757502 , 0.28306296, 0.60056979],
        [0.44406345, 0.87829328, 0.57014552]],

       [[0.60001272, 0.22717646, 0.62733168],
        [0.24121204, 0.51772594, 0.51141715],
        [0.40811443, 0.87239483, 0.09166809]],

       [[0.42252079, 0.4756871 , 0.75605344],
        [0.17925567, 0.08575455, 0.96888065],
        [0.41204525, 0.74116889, 0.9098866 ]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [41]:
arr = np.random.rand(10, 10)
min_val = arr.min()
max_val = arr.max()

print(arr)
print(min_val)
print(max_val)

[[0.15518462 0.01582404 0.03049235 0.23798746 0.29169413 0.72398312
  0.55855864 0.37045735 0.95630565 0.74698952]
 [0.51876408 0.58182639 0.15407516 0.94975181 0.30704232 0.02525849
  0.94055138 0.5146301  0.8196159  0.74973703]
 [0.37480746 0.12663777 0.98410577 0.71414068 0.20988168 0.67048956
  0.00960026 0.4666946  0.14289157 0.26556015]
 [0.52392397 0.69164731 0.52743212 0.95705758 0.45329179 0.59084404
  0.85771471 0.70326629 0.52867939 0.32674078]
 [0.71563671 0.75349511 0.68372442 0.83964144 0.42345732 0.23236238
  0.85583812 0.8369208  0.9952838  0.31922846]
 [0.03807379 0.83016762 0.96115127 0.66895898 0.80926736 0.58178699
  0.47323464 0.50442105 0.11814049 0.6617829 ]
 [0.10310825 0.81143513 0.38031766 0.27091692 0.03010652 0.5451266
  0.34094693 0.35404535 0.42959186 0.39551278]
 [0.85032996 0.01262911 0.17671937 0.13386591 0.17128783 0.16806228
  0.84101205 0.95998481 0.28260934 0.63917468]
 [0.68303664 0.23138045 0.63769185 0.95072058 0.46135832 0.47142299
  0.13196521 

#### 14. Create a random vector of size 30 and find the mean value

In [44]:
arr = np.random.rand(30)
print(arr)
np.mean(arr)

[0.38589097 0.61855189 0.18550328 0.24612277 0.87306674 0.61477728
 0.94329521 0.54745455 0.14712191 0.82556975 0.51302106 0.52670352
 0.99326887 0.22867271 0.03586203 0.48083309 0.97713889 0.94850142
 0.60782811 0.33173908 0.30774296 0.82284393 0.1434082  0.22039693
 0.0547644  0.35724863 0.68368945 0.81206752 0.83493728 0.18841758]


0.5152146662453561

#### 15. Create a 2d array with 1 on the border and 0 inside

In [57]:
def create_border_array(rows, cols):

    arr = np.zeros((rows, cols))
    arr[0, :] = 1 # top most row
    arr[-1, :] = 1 # bottom most row
    arr[:, 0] = 1 # left most column
    arr[:, -1] = 1 # right most column

    return arr

result = create_border_array(10, 10)
print(result)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [69]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

padded = np.pad(arr, pad_width = 1, mode = 'constant')
padded

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0],
       [0, 4, 5, 6, 0],
       [0, 7, 8, 9, 0],
       [0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [73]:
# nan
# False
# False
# nan
# True
# False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [84]:
values = [1, 2, 3, 4]

matrix = np.diag(values, k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [89]:
# create 8x8 array of zeros
checkerboard = np.zeros((8, 8), dtype = int)

checkerboard[1::2, ::2] = 1 # odd rows, even columns
checkerboard[::2, 1::2] = 1 # even rows, odd columns

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [91]:
x, y, z = np.unravel_index(99, (6, 7, 8))
print(f"using np.unravel_index : ({x}, {y}, {z})")

using np.unravel_index : (1, 5, 3)
